-- cleaning product table
SELECT p.[ProductKey]
      ,p.[ProductAlternateKey] as [Product Item Code]
    --  ,[ProductSubcategoryKey]
    --  ,[WeightUnitMeasureCode]
    --  ,[SizeUnitMeasureCode]
      ,p.[EnglishProductName] as [Product Name]
      --,[SpanishProductName]
      --,[FrenchProductName]
      --,[StandardCost]
     -- ,[FinishedGoodsFlag]
      ,p.[Color] as [Product Color]
     -- ,[SafetyStockLevel]
     -- ,[ReorderPoint]
     -- ,[ListPrice]
      ,p.[Size] as [Product Size]
     -- ,[SizeRange]
     -- ,[Weight]
     -- ,[DaysToManufacture]
      ,p.[ProductLine] as [Product Line]
      --,[DealerPrice]
     -- ,[Class]
     -- ,[Style]
      ,p.[ModelName] as [Model Name]
     -- ,[LargePhoto]
      ,[EnglishDescription]
     -- ,[FrenchDescription]
     -- ,[ChineseDescription]
     -- ,[ArabicDescription]
     -- ,[HebrewDescription]
      --,[ThaiDescription]
     -- ,[GermanDescription]
     -- ,[JapaneseDescription]
      --,[TurkishDescription]
     -- ,[StartDate]
     -- ,[EndDate]
      ,p.[Status] as [Product Status]
  FROM [AdventureWorksDW2019].[dbo].[DimProduct] p
  LEFT JOIN AdventureWorksDW2019.dbo.DimProductSubcategory ps ON ps.ProductSubcategoryKey = p.ProductSubcategoryKey
  LEFT JOIN AdventureWorksDW2019.dbo.DimProductCategory pc ON ps.ProductCategoryKey = pc.ProductCategoryKey 